version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: browsers:chrome71
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests
          command: npm run test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
